// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC86sXLFo4t0S5vWY45BIM_VTDkXt5cYCU',
    appId: '1:963800064485:web:b8f309c562ed062fba8f0c',
    messagingSenderId: '963800064485',
    projectId: 'fir-app-70428',
    authDomain: 'fir-app-70428.firebaseapp.com',
    storageBucket: 'fir-app-70428.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-hJyPH7ww3wpOyjtCdPvaq6-d_wsm6eU',
    appId: '1:963800064485:android:356a56b4618ca39fba8f0c',
    messagingSenderId: '963800064485',
    projectId: 'fir-app-70428',
    storageBucket: 'fir-app-70428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOFNrT3jAonlHuCOynZjjJ2Az8koa5bT4',
    appId: '1:963800064485:ios:bd1d917432b8ce38ba8f0c',
    messagingSenderId: '963800064485',
    projectId: 'fir-app-70428',
    storageBucket: 'fir-app-70428.appspot.com',
    iosClientId: '963800064485-7lr8qs0e8jgfsh1psi021tpfh27nesp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
